"""
guided_s03.py - session 3 guided page: demand, comparative statics, labour supply.

    Part 1  tangency  from the tangency to demand functions (the workhorse)
    Part 2  demand    demand and Engel curves (worksheet task 1, review question 3)
    Part 3  tariff    substitution and income effects (review question 4, Leon)
    Part 4  labour    labour supply (worksheet task 3, the windfall, Norway)
    Part 5  special   A3.1 quasilinear and A3.2 perfect substitutes

As in session 2, nothing here solves for the student: each step checks an
answer and draws the next piece of the figure.

Answers live in answers_s03.py as salted hashes. That file is generated by
answer_keys/s03_keys.py, which holds the plain answers and stays in the
private repo. Hash keys look like "d1.0" for the right
answer to box 0 of question d1, and "d1.0~4/9" for an expected mistake.
"""

import numpy as np

from guided import BOX, GuidedProblem, Question, tag

try:
    from answers_s03 import HASHES
except ImportError:                     # while the key file is being generated
    HASHES = {}

PS = lambda part: tag("problem", "Problem " + part)
NOTES = lambda where: tag("notes", "Notes " + where)


def H(key):
    return HASHES.get(key, "missing:" + key)


def M(messages):
    # {"d1.0~4/9": "hint"} -> {hash: "hint"}
    return {H(k): v for k, v in messages.items()}


INK, MUTE = "#1f2937", "#6b7280"
LINE, NEW, HALF, FILL = "#2563eb", "#ea580c", "#7c3aed", "#2563eb"
CURVE, GREEN, GREY = "#db2777", "#059669", "#9ca3af"
X1, X2 = "x<sub>1</sub>", "x<sub>2</sub>"
P1, P2 = "p<sub>1</sub>", "p<sub>2</sub>"


def _frame(ax, xmax, ymax, xlabel, ylabel):
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xlim(0, xmax)
    ax.set_ylim(0, ymax)
    ax.set_xlabel(xlabel, color=INK, fontsize=10, loc="right")
    ax.set_ylabel(ylabel, color=INK, fontsize=10, loc="top")


def _legend(ax, loc="upper right"):
    if not ax.get_legend_handles_labels()[0]:
        return                          # early stages have nothing labelled yet
    leg = ax.legend(loc=loc, fontsize=9, frameon=False)
    for t in leg.get_texts():
        t.set_color(INK)


def _dot(ax, x, y, label, dx=8, dy=4, colour=CURVE, ha="left"):
    ax.plot([x], [y], "o", color=colour, ms=7, zorder=6, clip_on=False)
    if label:
        ax.annotate(label, (x, y), textcoords="offset points", xytext=(dx, dy),
                    color=colour, fontsize=10.5, ha=ha)


def _budget(ax, p1, p2, m, **kw):
    ax.plot([0, m / p1], [m / p2, 0], **kw)


def _start(ax):
    ax.text(0.5, 0.5, "Answer step 1 to start drawing.", transform=ax.transAxes,
            ha="center", va="center", color=MUTE, fontsize=11)


STAYS = "It stays at 90"
RISES = "It rises"
FALLS = "It falls"
HALVES = "It halves"

SAME_SPEND = "It is the same at every price"
SP_RISES = "It rises as the price falls"
SP_FALLS = "It falls as the price falls"
SP_P2 = "It depends on p2"

DOUBLES = "It doubles"
LESS = "It rises, but by less than double"
MORE = "It more than doubles"
NOCHANGE = "It does not change"

LUX = "A luxury"
NEC = "A necessity"
INF = "An inferior good"
HOMO = "Neither: preferences are homothetic"

LUMP = "The lump-sum tax"
TARIFF = "The tariff"
EQUAL = "They are equally good: same revenue"
SPENT = "It depends on how the revenue is spent"

SUB_FALL = "It falls: she substitutes away from the good that got dearer"
SUB_RISE = "It rises"
SUB_SAME = "It stays the same"
SUB_ONLY1 = "Only good 1 changes"

INC = "The income effect: lost purchasing power, a parallel shift in"
SUB2 = "A second substitution effect"
DWL = "The deadweight loss"
REV = "The tariff revenue"

NEVER5 = "h* = 5 - 30/w: the second term shrinks as w rises but never reaches zero"
T_IS5 = "She only has 5 hours"
STOPS = "Above some wage she stops working"
CAP = "The reservation wage caps her hours"

H_FALL = "They fall: leisure is normal, so she buys more of it"
H_RISE = "They rise: she can afford to work more"
H_SAME = "They stay the same: the wage did not change"
H_DEP = "It depends on how strong the substitution effect is"

FLAT = "They don't respond: h* = T/2 at every wage"
FLAT_R = "They rise with the wage"
FLAT_F = "They fall with the wage"
FLAT_0 = "She does not work at all"

INC_WIN = "The income effect beat the substitution effect"
SUB_WIN = "The substitution effect beat the income effect"
INFER = "Leisure is an inferior good"
WRONG = "The model cannot explain it"

ALL2 = "Nothing: every extra krone goes to good 2"
BOTH = "It rises, like good 2"
PROP = "It rises in proportion to income"
DROPS = "It falls"

ONLY1 = "Only good 1, with all of her income"
ONLY2 = "Only good 2, with all of her income"
MIX = "A mix where the MRS equals the price ratio"
HALFS = "Half of her income on each"

N_NEITHER = "Neither: she buys none of it, so income cannot change it"
N_NORMAL = "Normal"
N_INFERIOR = "Inferior: demand is zero"
N_GIFFEN = "Giffen"

ORDINARY = "Ordinary: demand falls when its own price rises"
GIFFEN = "Giffen: demand rises when its own price rises"
NEITHER_OG = "Neither: demand jumps, so it is undefined"
DEPENDS_M = "It depends on income"


# ======================================================================
# Part 1: from the tangency to demand (notes p. 1-3)
# ======================================================================
# U = 2 ln x1 + 3 ln x2, p1 = 3, p2 = 2, m = 300. Given in the notes with
# the answer worked out, so this part is a warm-up on the four moves.

def draw_tangency(ax, stage):
    _frame(ax, 165, 240, "x1", "x2")
    _budget(ax, 3, 2, 300, color=LINE, lw=2.2, zorder=4, label="budget  3x1 + 2x2 = 300")
    ax.fill_between([0, 100], [150, 0], 0, color=FILL, alpha=0.07, lw=0)
    ax.annotate(r"$m/p_2$", (0, 150), textcoords="offset points", xytext=(6, 4),
                color=LINE, fontsize=10)
    ax.annotate(r"$m/p_1$", (100, 0), textcoords="offset points", xytext=(0, 6),
                ha="center", color=LINE, fontsize=10)

    if stage >= 1:
        xs = np.array([0, 100])
        ax.plot(xs, 2.25 * xs, color=MUTE, lw=1.2, ls=":",
                label=r"tangency: $p_2x_2 = \frac{\beta}{\alpha}\,p_1x_1$")
    if stage >= 2:
        xs = np.linspace(8, 165, 300)
        level = 2 * np.log(40) + 3 * np.log(90)
        ax.plot(xs, np.exp((level - 2 * np.log(xs)) / 3), color=CURVE, lw=2, zorder=4)
        _dot(ax, 40, 90, "A", 8, 2)
    if stage >= 3:
        ax.text(0.98, 0.62, r"good 1 gets the share $\frac{\alpha}{\alpha+\beta}$ of $m$",
                transform=ax.transAxes, ha="right", color=INK, fontsize=11)
    if stage >= 4:
        _budget(ax, 3, 2, 450, color=HALF, lw=1.8, ls="--", alpha=1 if stage == 4 else 0.45,
                label="Try it (b): more income")
        _dot(ax, 60, 135, "(b)", 8, 0, colour=HALF)
    if stage >= 5:
        _budget(ax, 6, 2, 300, color=NEW, lw=1.8, ls="--", alpha=1 if stage == 5 else 0.45,
                label=r"Try it (c): a higher $p_1$")
        _dot(ax, 20, 90, "(c)", -10, 6, colour=NEW, ha="right")
    if stage >= 6:
        ax.axhline(90, color=NEW, lw=1, ls=":", xmax=0.5)
        ax.text(84, 80, r"$x_2$ unchanged", color=NEW, fontsize=10)
    _legend(ax)


TANGENCY_QUESTIONS = [
    Question(
        "d1",
        "U = 2 ln x<sub>1</sub> + 3 ln x<sub>2</sub>, %s = 3, %s = 2, m = 300. "
        "Divide the first-order conditions to kill &lambda;. The tangency says "
        "x<sub>2</sub> is a fixed multiple of x<sub>1</sub>. Which multiple?"
        % (P1, P2),
        form=["x<sub>2</sub> =", BOX, "&middot; x<sub>1</sub>"],
        answers=[H("d1.0")],
        mistakes=M({
            "d1.0~4/9": "Upside down. Solve 2/(3x<sub>1</sub>) = 3/(2x<sub>2</sub>) "
                        "for x<sub>2</sub>.",
            "d1.0~3/2": "That ignores the prices. The MRS has to equal %s/%s." % (P1, P2),
            "d1.0~2/3": "That ignores the prices. The MRS has to equal %s/%s." % (P1, P2),
        }),
        hints=["FOC 1 gives &lambda; = 2/(3x<sub>1</sub>), FOC 2 gives "
               "&lambda; = 3/(2x<sub>2</sub>). Set them equal."],
        explain="The tangency fixes the ratio of the goods, not the level."),

    Question(
        "d2",
        "Put the tangency into the budget 3x<sub>1</sub> + 2x<sub>2</sub> = 300. "
        "What is the bundle?",
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("d2.0"), H("d2.1")],
        mistakes=M({
            "d2.0~60": "That is half of income on good 1. The weights are 2 and 3, "
                       "not equal.",
            "d2.0~100": "That is the intercept: all income on good 1.",
            "d2.1~150": "That is the intercept: all income on good 2.",
            "d2.1~60": "Use the tangency from step 1 to get x<sub>2</sub>.",
        }),
        hints=["Replace x<sub>2</sub> by its multiple of x<sub>1</sub>, and you have "
               "one equation in x<sub>1</sub>."],
        explain="The budget fixes the level. Check it: the bundle exhausts the budget."),

    Question(
        "d3",
        "What share of income goes to good 1? Write it as a fraction.",
        form=["share =", BOX],
        answers=[H("d3.0")],
        mistakes=M({
            "d3.0~3/5": "That is good 2's share.",
            "d3.0~1/2": "Only with equal weights. Here they are 2 and 3.",
            "d3.0~2/3": "Divide by the sum of the weights, not by the other weight.",
        }),
        hints=["Spending on good 1 is %s&middot;x<sub>1</sub>. Divide by m." % P1],
        explain="x<sub>1</sub>* = &alpha;/(&alpha; + &beta;) &middot; m/%s: log and "
                "Cobb-Douglas utility give each good a fixed budget share." % P1),

    Question(
        "d4",
        "Same tastes and prices. A colleague buys 135 units of good 2. What is "
        "her income?",
        form=["m =", BOX],
        answers=[H("d4.0")],
        mistakes=M({
            "d4.0~270": "That is only what she spends on good 2.",
            "d4.0~300": "That is the original income. She buys more of good 2 than 90.",
        }),
        hints=["The tangency still holds: find her x<sub>1</sub> first, then add up "
               "her spending."],
        explain="Running the machinery backwards reads income off a choice."),

    Question(
        "d5",
        "Income is 300 again, but you observe a consumer buying 20 units of good 1. "
        "What %s does she face?" % P1,
        form=["%s =" % P1, BOX],
        answers=[H("d5.0")],
        mistakes=M({
            "d5.0~15": "That assumes she spends everything on good 1. She only spends "
                       "her share on it.",
            "d5.0~3": "That is the old price. Would she then buy only 20?",
        }),
        hints=["Spending on good 1 is still a fixed share of 300."],
        explain="The share rule works in every direction: quantities, income or prices."),

    Question(
        "d6",
        "In that last case, what happened to x<sub>2</sub> compared with the "
        "original bundle?",
        choices=[STAYS, RISES, FALLS, HALVES],
        answers=[H("d6.c")],
        mistakes=M({
            "d6.c~" + RISES: "What share of income goes to good 2, and did income or "
                             "%s change?" % P2,
            "d6.c~" + FALLS: "What share of income goes to good 2, and did income or "
                             "%s change?" % P2,
            "d6.c~" + HALVES: "Only %s changed. Does x<sub>2</sub> = &beta;/(&alpha;+&beta;) "
                              "&middot; m/%s contain %s?" % (P1, P2, P1),
        }),
        explain="Under log utility the other good's demand ignores this price. "
                "Convenient, and special: keep it in mind for the tariff."),
]

tangency = GuidedProblem(
    "Part 1 &middot; From the tangency to demand",
    "The notes' workhorse: U = 2 ln x<sub>1</sub> + 3 ln x<sub>2</sub>, prices "
    "%s = 3 and %s = 2, income m = 300. Run the four moves, then run them "
    "backwards." % (P1, P2),
    TANGENCY_QUESTIONS, draw_tangency,
    outro="That share rule is the workhorse of the session. Part 2 turns it into "
          "curves.",
    sources=[NOTES("p. 1&ndash;3")],
)


# ======================================================================
# Part 2: demand and Engel curves (worksheet task 1, review question 3)
# ======================================================================
# U = ln x1 + ln x2 with m = 120. The worksheet gives the point (10, 6).

DEMAND_PTS = [(15, 4), (20, 3), (30, 2)]


def draw_demand(fig, stage):
    ax, ex = fig.subplots(1, 2)
    _frame(ax, 36, 7.5, "x1", "p1")
    ax.set_title("Demand curve", loc="left", color=INK, fontsize=10)
    _dot(ax, 10, 6, "(10, 6) given", 8, 2, colour=LINE)
    if stage >= 1:
        ax.text(0.97, 0.92, r"$x_1^* = \frac{m}{2p_1}$", transform=ax.transAxes,
                ha="right", color=INK, fontsize=12)
    for i, (x, p) in enumerate(DEMAND_PTS):
        if stage >= i + 2:
            _dot(ax, x, p, "(%d, %d)" % (x, p), 6, 4)
    if stage >= 4:
        xs = np.linspace(8.2, 36, 200)
        ax.plot(xs, 60 / xs, color=CURVE, lw=1.8, zorder=3)
    if stage >= 5:
        for x, p in ((10, 6), (30, 2)):
            ax.fill_between([0, x], 0, p, color=CURVE, alpha=0.08, lw=0)
        ax.text(0.97, 0.55, r"$p_1 x_1$ the same everywhere", transform=ax.transAxes,
                ha="right", color=CURVE, fontsize=9.5)

    _frame(ex, 70, 260, "x1", "income m")
    ex.set_title("Engel curve", loc="left", color=INK, fontsize=10)
    if stage < 6:
        ex.text(0.5, 0.5, "?", transform=ex.transAxes, ha="center", va="center",
                color=MUTE, fontsize=28)
        return
    ms = np.linspace(0, 250, 50)
    ex.plot(ms / 4, ms, color=CURVE, lw=2, label="Cobb-Douglas: a straight ray")
    _dot(ex, 30, 120, "", colour=CURVE)
    _dot(ex, 60, 240, "", colour=CURVE)
    ex.annotate("", xy=(60, 240), xytext=(30, 120),
                arrowprops=dict(arrowstyle="->", color=MUTE, lw=1))
    if stage >= 7:
        mm = np.linspace(60, 250, 100)
        ex.plot(25 * (mm / 120) ** -0.5, mm, color=NEW, lw=1.6, ls="--",
                label=r"inferior, $\eta < 0$")
    if stage >= 8:
        mm = np.linspace(20, 250, 100)
        ex.plot(30 * (mm / 120) ** 1.6, mm, color=HALF, lw=1.6, ls="--",
                label=r"luxury, $\eta > 1$")
    _legend(ex, loc="lower right")
    fig.subplots_adjust(wspace=0.25)


DEMAND_QUESTIONS = [
    Question(
        "e1",
        "Worksheet task 1: U = ln x<sub>1</sub> + ln x<sub>2</sub> with income 120. "
        "Derive the demand for good 1.",
        form=["x<sub>1</sub>* =", BOX, "/ %s" % P1],
        answers=[H("e1.0")],
        mistakes=M({
            "e1.0~120": "That spends all of income on good 1. With equal weights, "
                        "what share does it get?",
            "e1.0~30": "Too small: the share is one half, not one quarter.",
        }),
        hints=["Equal weights: half of income on each good."],
        explain="x<sub>1</sub>* = m/(2%s): a demand <i>function</i> of the price." % P1),
    Question("e2", "Plot the bundle at %s = 4: how much good 1?" % P1,
             form=["x<sub>1</sub> =", BOX], answers=[H("e2.0")],
             mistakes=M({"e2.0~30": "Use your demand function, not income over price."}),
             explain="A second point on the demand curve."),
    Question("e3", "At %s = 3?" % P1, form=["x<sub>1</sub> =", BOX], answers=[H("e3.0")],
             mistakes=M({"e3.0~40": "Use your demand function, not income over price."}),
             explain="A third point."),
    Question("e4", "At %s = 2?" % P1, form=["x<sub>1</sub> =", BOX], answers=[H("e4.0")],
             mistakes=M({"e4.0~60": "Use your demand function, not income over price."}),
             explain="Join the dots: a hyperbola, sloping down."),
    Question(
        "e5",
        "Look at the four points. What happens to total spending on good 1, "
        "%s&middot;x<sub>1</sub>, along this demand curve?" % P1,
        choices=[SAME_SPEND, SP_RISES, SP_FALLS, SP_P2],
        answers=[H("e5.c")],
        mistakes=M({
            "e5.c~" + SP_RISES: "Multiply price by quantity at two of your points.",
            "e5.c~" + SP_FALLS: "Multiply price by quantity at two of your points.",
            "e5.c~" + SP_P2: "Does m/(2%s) contain %s?" % (P1, P2),
        }),
        explain="Spending is fixed at m/2: unit-elastic demand. The shaded "
                "rectangles have the same area."),
    Question(
        "e6",
        "Now hold prices fixed and double income. What happens to x<sub>1</sub>*?",
        choices=[DOUBLES, LESS, MORE, NOCHANGE],
        answers=[H("e6.c")],
        mistakes=M({
            "e6.c~" + LESS: "x<sub>1</sub>* = m/(2%s). What does doubling m do?" % P1,
            "e6.c~" + MORE: "x<sub>1</sub>* = m/(2%s). What does doubling m do?" % P1,
            "e6.c~" + NOCHANGE: "That is quasilinear demand. Here m is in the formula.",
        }),
        explain="The Engel curve is a straight ray: income elasticity 1, constant "
                "budget shares, homothetic preferences."),
    Question(
        "e7",
        "Review question 3: a market-research firm estimates the income elasticity of "
        "instant noodles at &eta; = &minus;0.5. What kind of good is that?",
        choices=[LUX, NEC, INF, HOMO],
        answers=[H("e7.c")],
        mistakes=M({
            "e7.c~" + LUX: "A luxury needs &eta; above 1.",
            "e7.c~" + NEC: "A necessity has &eta; between 0 and 1. What does a "
                           "negative &eta; say happens when income rises?",
            "e7.c~" + HOMO: "Homothetic means &eta; = 1 for every good.",
        }),
        explain="&eta; &lt; 0: demand falls as income rises. The Engel curve "
                "bends back."),
    Question(
        "e8",
        "And streaming subscriptions, with &eta; = 1.6?",
        choices=[LUX, NEC, INF, HOMO],
        answers=[H("e8.c")],
        mistakes=M({
            "e8.c~" + NEC: "A necessity has &eta; between 0 and 1.",
            "e8.c~" + INF: "Inferior needs a negative &eta;.",
            "e8.c~" + HOMO: "Homothetic means &eta; = 1 for every good.",
        }),
        explain="&eta; &gt; 1: the budget share grows with income. Jobs in luxury "
                "industries ride the business cycle."),
]

demand = GuidedProblem(
    "Part 2 &middot; Demand and Engel curves",
    "Vary one thing at a time. Change %s and the bundles trace the demand "
    "curve; change m and they trace the Engel curve." % P1,
    DEMAND_QUESTIONS, draw_demand, figsize=(7.6, 4.0), whole_figure=True,
    outro="Same machinery, two slices. Part 3 asks what a price change does to "
          "you, not just to the quantity.",
    sources=[NOTES("p. 4&ndash;8"), NOTES("p. 17, worksheet"), NOTES("p. 18, review question 3")],
)


# ======================================================================
# Part 3: the tariff, in two steps (review question 4: Leon)
# ======================================================================
# U = ln x1 + ln x2, m = 80, p1 = 1, p2 = 2, a 100% tariff on good 2.

def draw_tariff(ax, stage):
    _frame(ax, 90, 46, "x1", "x2")
    _budget(ax, 1, 2, 80, color=LINE, lw=2.2, zorder=4, label="before the tariff")
    ax.fill_between([0, 80], [40, 0], 0, color=FILL, alpha=0.06, lw=0)
    xs = np.linspace(17, 90, 300)
    if stage >= 1:
        ax.plot(xs, 800 / xs, color=CURVE, lw=1.8, zorder=4)
        ax.text(86, 800 / 86 + 1.2, r"$U_0$", color=CURVE, fontsize=11)
        _dot(ax, 40, 20, "A", 6, 6)
    if stage >= 2:
        _budget(ax, 1, 4, 80, color=NEW, lw=2, ls="--", zorder=4, label="with the tariff")
    if stage >= 3:
        xs2 = np.linspace(4.5, 90, 300)
        ax.plot(xs2, 400 / xs2, color=CURVE, lw=1.2, ls=":", zorder=4)
        _dot(ax, 40, 10, "C", 6, -14)
    if stage >= 4:
        # Down and left of C: the B arrows arrive from the upper right later.
        ax.annotate(r"revenue $= \tau\, p_2\, x_2^C$", (40, 10), textcoords="data",
                    xytext=(4, 3), color=NEW, fontsize=10,
                    arrowprops=dict(arrowstyle="-", color=NEW, lw=0.8))
    if stage >= 5:
        _budget(ax, 1, 2, 60, color=GREEN, lw=1.8, ls=":", zorder=4,
                label="lump sum, same revenue")
        xs3 = np.linspace(10.5, 90, 300)
        ax.plot(xs3, 450 / xs3, color=GREEN, lw=1, alpha=0.7)
        _dot(ax, 30, 15, "D", -10, 4, colour=GREEN, ha="right")
    if stage >= 6:
        ax.text(0.98, 0.6, "D is on a higher curve than C:\nthe gap is the deadweight loss",
                transform=ax.transAxes, ha="right", color=GREEN, fontsize=9.5)
    if stage >= 7:
        bx, by = 800 ** 0.5 * 2, 800 ** 0.5 / 2          # cheapest bundle on U0 at (1, 4)
        ax.plot([0, by * 4 + bx], [by + bx / 4, 0], color=GREY, lw=1.2, ls="--",
                label="new prices, old utility")
        _dot(ax, bx, by, "B", 8, 2, colour=INK)
        ax.annotate("", xy=(bx, by), xytext=(40, 20),
                    arrowprops=dict(arrowstyle="-|>", color=INK, lw=1.4,
                                    shrinkA=6, shrinkB=6))
        ax.text((40 + bx) / 2 + 1, (20 + by) / 2 + 1.5, "substitution", color=INK,
                fontsize=9)
    if stage >= 8:
        ax.annotate("", xy=(40, 10), xytext=(bx, by),
                    arrowprops=dict(arrowstyle="-|>", color=INK, lw=1.4,
                                    shrinkA=6, shrinkB=6))
        ax.text((40 + bx) / 2 + 2, (10 + by) / 2 - 3, "income", color=INK, fontsize=9)
    _legend(ax)


TARIFF_QUESTIONS = [
    Question(
        "f1",
        "Leon has U = ln x<sub>1</sub> + ln x<sub>2</sub>, m = 80, %s = 1, %s = 2. "
        "What does he buy before any tariff?" % (P1, P2),
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("f1.0"), H("f1.1")],
        mistakes=M({
            "f1.0~80": "That is the intercept: all income on good 1.",
            "f1.1~40": "Half of income goes to good 2, but divide by its price.",
        }),
        hints=["Equal weights: half of income on each good, divided by its price."],
        explain="Point A, on the curve U<sub>0</sub>."),
    Question(
        "f2",
        "The government puts a 100% tariff on good 2. What price does Leon now pay "
        "for good 2?",
        form=["%s' =" % P2, BOX],
        answers=[H("f2.0")],
        mistakes=M({"f2.0~3": "A 100% tariff adds 100% of the price.",
                    "f2.0~2": "That is the price before the tariff."}),
        explain="The budget line pivots in around the x<sub>1</sub>-intercept."),
    Question(
        "f3",
        "What does Leon buy with the tariff?",
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("f3.0"), H("f3.1")],
        mistakes=M({
            "f3.0~20": "Does good 1's price or income change? Then its share doesn't either.",
            "f3.1~20": "That is the old bundle. Use the new price of good 2.",
        }),
        explain="Point C. Good 1 stays put, as in Part 1: log utility."),
    Question(
        "f4",
        "How much revenue does the tariff raise, &tau;&middot;%s&middot;x<sub>2</sub>?" % P2,
        form=["revenue =", BOX],
        answers=[H("f4.0")],
        mistakes=M({
            "f4.0~40": "That is everything Leon pays for good 2. The government keeps "
                       "only the tariff part.",
            "f4.0~10": "Multiply by the tariff per unit, not by 1.",
        }),
        hints=["The tariff per unit is &tau;&middot;%s, with the old price." % P2],
        explain="That is what the government gets."),
    Question(
        "f5",
        "Instead, the government takes the same amount as a lump sum and leaves "
        "prices alone. What does Leon buy then?",
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("f5.0"), H("f5.1")],
        mistakes=M({
            "f5.0~40": "Income is lower now. Recompute with m minus the revenue.",
            "f5.1~10": "That is the tariff bundle. Prices are back to the old ones.",
            "f5.1~15/2": "Prices are back to the old ones: %s = 2." % P2,
        }),
        explain="Point D. The lump-sum line passes through C, at the old slope."),
    Question(
        "f6",
        "Rank the two by x<sub>1</sub>&middot;x<sub>2</sub>. Which policy does Leon "
        "prefer?",
        choices=[LUMP, TARIFF, EQUAL, SPENT],
        answers=[H("f6.c")],
        mistakes=M({
            "f6.c~" + TARIFF: "Compute x<sub>1</sub>&middot;x<sub>2</sub> at C and at D.",
            "f6.c~" + EQUAL: "Same revenue, but compute x<sub>1</sub>&middot;x<sub>2</sub> "
                             "at C and at D.",
            "f6.c~" + SPENT: "Both raise the same amount, so spending it is the same "
                             "either way.",
        }),
        explain="Same money taken, but the tariff also distorts a relative price. "
                "That is the deadweight loss."),
    Question(
        "f7",
        "Split the move A &rarr; C in two. First slide along U<sub>0</sub> until the "
        "slope matches the new prices: point B. From A to B, what happens to x<sub>2</sub>?",
        choices=[SUB_FALL, SUB_RISE, SUB_SAME, SUB_ONLY1],
        answers=[H("f7.c")],
        mistakes=M({
            "f7.c~" + SUB_RISE: "Good 2 got relatively dearer. Along one curve, do you "
                                "buy more or less of it?",
            "f7.c~" + SUB_SAME: "The slope changes, so the point on U<sub>0</sub> must move.",
            "f7.c~" + SUB_ONLY1: "Along an indifference curve, more of one means less "
                                 "of the other.",
        }),
        explain="A &rarr; B is the substitution effect: utility held fixed, relative "
                "price changed."),
    Question(
        "f8",
        "And B &rarr; C?",
        choices=[INC, SUB2, DWL, REV],
        answers=[H("f8.c")],
        mistakes=M({
            "f8.c~" + SUB2: "B and C face the same prices. What differs between their "
                            "budget lines?",
            "f8.c~" + DWL: "The deadweight loss compares C with D, not B with C.",
            "f8.c~" + REV: "Revenue is the government's side. B &rarr; C is about Leon.",
        }),
        explain="B &rarr; C is the income effect: same prices, less purchasing power. "
                "For a normal good both effects push the same way."),
]

tariff = GuidedProblem(
    "Part 3 &middot; The tariff, in two steps",
    "Review question 4. Leon has U = ln x<sub>1</sub> + ln x<sub>2</sub>, income "
    "m = 80, and prices %s = 1 and %s = 2. Then the government puts a 100%% "
    "tariff on good 2." % (P1, P2),
    TARIFF_QUESTIONS, draw_tariff, figsize=(6.4, 4.8),
    outro="Two channels, different welfare effects. Part 4 runs the same "
          "decomposition on the wage.",
    sources=[NOTES("p. 18, review question 4"), NOTES("p. 9&ndash;11")],
)


# ======================================================================
# Part 4: labour supply (worksheet task 3, the windfall, Norway)
# ======================================================================
# U = ln C + ln L, m = 60, T = 10, consumption price 1: h* = 5 - 30/w.

SUPPLY_PTS = [(2, 10), (3, 15), (4, 30)]


def draw_labour(ax, stage):
    _frame(ax, 6.2, 37, "hours worked h", "wage w")
    for i, (h, w) in enumerate(SUPPLY_PTS):
        if stage >= i + 1:
            _dot(ax, h, w, "(%d, %d)" % (h, w), 8, -4)
    ws = np.linspace(6, 37, 200)
    if stage >= 4:
        ax.plot(5 - 30 / ws, ws, color=CURVE, lw=2, zorder=4,
                label=r"$h^* = T/2 - m/(2w)$")
        _dot(ax, 0, 6, r"$w_R$", 8, -4, colour=LINE)
    if stage >= 5:
        ax.axvline(5, color=MUTE, lw=1, ls=":")
        ax.text(5.05, 2, r"$T/2$", color=MUTE, fontsize=10)
    if stage >= 6:
        ws2 = np.linspace(9, 37, 200)
        ax.plot(5 - 45 / ws2, ws2, color=HALF, lw=1.6, ls="--",
                alpha=1 if stage == 6 else 0.45, label="windfall: more m")
    if stage >= 7:
        ax.plot([5, 5], [0.3, 37], color=NEW, lw=1.8, ls="--",
                alpha=1 if stage == 7 else 0.45, label=r"$m = 0$")
    if stage >= 8:
        b = np.linspace(6, 37, 200)
        hb = 5.2 * (1 - np.exp(-(b - 6) / 5)) - 0.12 * (b - 6)
        ax.plot(hb, b, color=GREY, lw=1.6, label="illustration: a backward bend")
    _legend(ax, loc="upper left")


LABOUR_QUESTIONS = [
    Question(
        "g1",
        "Worksheet task 3: U = ln C + ln L, m = 60, T = 10, consumption price 1. "
        "How many hours does she work at w = 10?",
        form=["h* =", BOX],
        answers=[H("g1.0")],
        mistakes=M({
            "g1.0~8": "That is leisure L*. Hours are T &minus; L.",
            "g1.0~5": "That is T/2, with m = 0. Here m = 60.",
        }),
        hints=["The notes' worked example: L* = m/(2w) + T/2, and h* = T &minus; L*."],
        explain="A first point on her labour supply curve."),
    Question("g2", "At w = 15?", form=["h* =", BOX], answers=[H("g2.0")],
             mistakes=M({"g2.0~7": "That is leisure. Hours are T &minus; L."}),
             explain="A second point."),
    Question("g3", "At w = 30?", form=["h* =", BOX], answers=[H("g3.0")],
             mistakes=M({"g3.0~6": "That is leisure. Hours are T &minus; L."}),
             explain="A third point."),
    Question(
        "g4",
        "Below which wage does she not work at all? That is her reservation wage.",
        form=["w<sub>R</sub> =", BOX],
        answers=[H("g4.0")],
        mistakes=M({
            "g4.0~10": "That is T. Set h* = 0 and solve for w.",
            "g4.0~3": "Close: check the factor of 2.",
            "g4.0~1/6": "Upside down.",
        }),
        hints=["Set h* = 0 in h* = T/2 &minus; m/(2w)."],
        explain="w<sub>R</sub> = m/T: the curve starts there."),
    Question(
        "g5",
        "Worksheet: what stops h* from ever reaching 5 hours?",
        choices=[NEVER5, T_IS5, STOPS, CAP],
        answers=[H("g5.c")],
        mistakes=M({
            "g5.c~" + T_IS5: "T is 10.",
            "g5.c~" + STOPS: "Look at your three points: do hours ever fall?",
            "g5.c~" + CAP: "The reservation wage is where hours start, not where "
                           "they stop.",
        }),
        explain="h* approaches T/2 from below. Here substitution wins at every wage: "
                "no backward bend."),
    Question(
        "g6",
        "A windfall: non-labour income m rises, the wage stays the same. Leisure is "
        "a normal good. What happens to hours worked?",
        choices=[H_FALL, H_RISE, H_SAME, H_DEP],
        answers=[H("g6.c")],
        mistakes=M({
            "g6.c~" + H_RISE: "More money and leisure is normal: does she want more "
                              "or less leisure?",
            "g6.c~" + H_SAME: "The wage didn't change, but income did.",
            "g6.c~" + H_DEP: "No price moved, so there is no substitution effect at all.",
        }),
        explain="A pure income effect: richer, working less."),
    Question(
        "g7",
        "Back to the formula h* = T/2 &minus; m/(2w). If m = 0, how do hours respond "
        "to the wage?",
        choices=[FLAT, FLAT_R, FLAT_F, FLAT_0],
        answers=[H("g7.c")],
        mistakes=M({
            "g7.c~" + FLAT_R: "Put m = 0 into the formula.",
            "g7.c~" + FLAT_F: "Put m = 0 into the formula.",
            "g7.c~" + FLAT_0: "Put m = 0 into the formula.",
        }),
        explain="The two effects cancel to the krone. A property of log utility, not "
                "of the world."),
    Question(
        "g8",
        "Over 40 years Norwegian real wages rose by about 70% while hours per "
        "worker fell. In the model, what does that say?",
        choices=[INC_WIN, SUB_WIN, INFER, WRONG],
        answers=[H("g8.c")],
        mistakes=M({
            "g8.c~" + SUB_WIN: "Substitution says a dearer hour of leisure means work "
                               "more. Did hours rise?",
            "g8.c~" + INFER: "It is enough for leisure to be normal: then a wage rise "
                             "has an income effect towards more leisure.",
            "g8.c~" + WRONG: "A wage rise has two effects that pull opposite ways. Can "
                             "one of them explain falling hours?",
        }),
        explain="Norway sits on the backward-bending stretch: a claim about "
                "magnitudes at Norwegian wages, not a law of nature."),
]

labour = GuidedProblem(
    "Part 4 &middot; Labour supply",
    "The notes' labour supply model with the worksheet's numbers: "
    "U = ln C + ln L, non-labour income m = 60, T = 10 hours. Build her supply "
    "curve, then push on it.",
    LABOUR_QUESTIONS, draw_labour, figsize=(6.4, 4.6),
    outro="Substitution says work more, income says work less. Which wins is an "
          "empirical question.",
    sources=[NOTES("p. 12&ndash;17")],
)


# ======================================================================
# Part 5: the two special cases (A3.1 quasilinear, A3.2 substitutes)
# ======================================================================

def draw_special(fig, stage):
    ql, ps = fig.subplots(1, 2)
    _frame(ql, 11, 7, "x1", "x2")
    ql.set_title(r"A3.1: $u = \ln x_1 + x_2$", loc="left", color=INK, fontsize=10)
    xs = np.linspace(0.15, 11, 200)
    for k in (2.2, 3.4, 4.6, 5.8):
        ql.plot(xs, k - np.log(xs), color=CURVE, lw=0.9, ls=":", alpha=0.6)
    if stage >= 1:
        ql.axvline(2, color=MUTE, lw=1, ls="--")
        ql.text(2.15, 6.4, r"$x_1$ fixed", color=MUTE, fontsize=9.5)
    if stage >= 2:
        _budget(ql, 2, 4, 20, color=LINE, lw=2, label="m = 20")
        _dot(ql, 2, 4, "(2, 4)", 8, 2)
    if stage >= 3:
        _budget(ql, 2, 4, 3, color=NEW, lw=2, ls="--", label=r"m = 3 < $p_2$")
        _dot(ql, 1.5, 0, "corner", 4, 8, colour=NEW)
        _legend(ql)

    _frame(ps, 8, 6, "x1", "x2")
    ps.set_title(r"A3.2: $u = x_1 + x_2$", loc="left", color=INK, fontsize=10)
    if stage < 4:
        ps.text(0.5, 0.5, "?", transform=ps.transAxes, ha="center", va="center",
                color=MUTE, fontsize=28)
        return
    for k in (2, 4, 6):
        ps.plot([0, k], [k, 0], color=CURVE, lw=0.9, ls=":", alpha=0.6)
    _budget(ps, 10, 15, 60, color=LINE, lw=2, label=r"$p_1 < p_2$")
    _dot(ps, 6, 0, "everything on good 1", -6, 10, ha="right")
    if stage >= 5:
        ps.text(0.97, 0.9, "good 2: zero at every income", transform=ps.transAxes,
                ha="right", color=INK, fontsize=9.5)
    if stage >= 6:
        ps.text(0.97, 0.8, r"$x_1 = m/p_1$ falls as $p_1$ rises", transform=ps.transAxes,
                ha="right", color=INK, fontsize=9.5)
    _legend(ps, loc="center right")
    fig.subplots_adjust(wspace=0.25)


SPECIAL_QUESTIONS = [
    Question(
        "h1",
        "A3.1: u = ln x<sub>1</sub> + x<sub>2</sub>. In the interior case, income "
        "rises. What happens to x<sub>1</sub>*?",
        choices=[ALL2, BOTH, PROP, DROPS],
        answers=[H("h1.c")],
        mistakes=M({
            "h1.c~" + BOTH: "The MRS is 1/x<sub>1</sub>. Does it depend on x<sub>2</sub>?",
            "h1.c~" + PROP: "That is Cobb-Douglas. Here the MRS depends on x<sub>1</sub> only.",
            "h1.c~" + DROPS: "Nothing makes good 1 inferior here. Does the tangency "
                             "involve m at all?",
        }),
        explain="The indifference curves are vertical shifts of each other, so the "
                "tangency pins x<sub>1</sub> whatever m is."),
    Question(
        "h2",
        "A3.1 with numbers: %s = 2, %s = 4, m = 20. What is the bundle?" % (P1, P2),
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("h2.0"), H("h2.1")],
        mistakes=M({
            "h2.0~10": "That is the intercept. The tangency 1/x<sub>1</sub> = "
                       "%s/%s pins x<sub>1</sub>." % (P1, P2),
            "h2.0~1/2": "Upside down: 1/x<sub>1</sub> = %s/%s." % (P1, P2),
            "h2.1~5": "Good 2 gets what is left after good 1.",
        }),
        hints=["The FOCs give 1/x<sub>1</sub> = %s/%s. Then spend the rest on good 2." % (P1, P2)],
        explain="Spending on good 1 is exactly %s, whatever %s is." % (P2, P1)),
    Question(
        "h3",
        "Now income is only m = 3, less than %s. What is the bundle?" % P2,
        form=["x<sub>1</sub> =", BOX, "&nbsp; x<sub>2</sub> =", BOX],
        answers=[H("h3.0"), H("h3.1")],
        mistakes=M({
            "h3.0~2": "Can she afford the interior x<sub>1</sub> and still have "
                      "x<sub>2</sub> &ge; 0?",
            "h3.1~-1/4": "x<sub>2</sub> cannot be negative.",
        }),
        hints=["The interior formula gives a negative x<sub>2</sub>. Set x<sub>2</sub> = 0 "
               "and spend everything on good 1."],
        explain="A corner: good 1 is rationed by income and good 2 is not bought."),
    Question(
        "h4",
        "A3.2: u = x<sub>1</sub> + x<sub>2</sub>, m = 60, %s = 10, %s = 15. What "
        "does the consumer buy?" % (P1, P2),
        choices=[ONLY1, ONLY2, MIX, HALFS],
        answers=[H("h4.c")],
        mistakes=M({
            "h4.c~" + ONLY2: "Which good gives a unit of utility more cheaply?",
            "h4.c~" + MIX: "The MRS is constant at 1 and never equals %s/%s here." % (P1, P2),
            "h4.c~" + HALFS: "That is Cobb-Douglas with equal weights.",
        }),
        explain="Straight indifference lines against a straight budget: the corner "
                "with the cheaper good."),
    Question(
        "h5",
        "In that case, is good 2 normal or inferior?",
        choices=[N_NEITHER, N_NORMAL, N_INFERIOR, N_GIFFEN],
        answers=[H("h5.c")],
        mistakes=M({
            "h5.c~" + N_NORMAL: "Normal means demand rises with income. Does it?",
            "h5.c~" + N_INFERIOR: "Inferior means demand falls with income. Can zero fall?",
            "h5.c~" + N_GIFFEN: "Giffen is about its own price, not income.",
        }),
        explain="Neither. The solutions call this out: zero cannot fall."),
    Question(
        "h6",
        "Is good 1 ordinary or Giffen?",
        choices=[ORDINARY, GIFFEN, NEITHER_OG, DEPENDS_M],
        answers=[H("h6.c")],
        mistakes=M({
            "h6.c~" + GIFFEN: "x<sub>1</sub> = m/%s. What happens when %s rises?" % (P1, P1),
            "h6.c~" + NEITHER_OG: "Where demand jumps, it jumps down, so it still falls.",
            "h6.c~" + DEPENDS_M: "Income decides how much, not whether demand falls.",
        }),
        explain="Ordinary. No Giffen good is possible here: income never decides "
                "which good to buy."),
]

special = GuidedProblem(
    "Part 5 &middot; Two special cases",
    "The in-person problems: quasilinear tastes (A3.1) and perfect substitutes "
    "(A3.2). Where the tangency rule bends, and where it breaks.",
    SPECIAL_QUESTIONS, draw_special, figsize=(7.6, 4.0), whole_figure=True,
    outro="That is session 3. Next session adds time: saving and borrowing.",
    sources=[PS("A3.1"), PS("A3.2")],
)


# ======================================================================
# Where every step comes from
# ======================================================================
# Page numbers are the printed pages of s03_notes.pdf. Problem numbers are
# the in-person problems (A3_handout.pdf).

STEP_SOURCES = {
    "d1": NOTES("p. 1&ndash;2 &middot; worked example"),
    "d2": NOTES("p. 2 &middot; worked example"),
    "d3": NOTES("p. 3 &middot; the share formula"),
    "d4": NOTES("p. 2 &middot; Try it (b)"),
    "d5": NOTES("p. 2 &middot; Try it (c)"),
    "d6": NOTES("p. 3"),

    "e1": NOTES("p. 17 &middot; worksheet task 1"),
    "e2": NOTES("p. 17 &middot; worksheet task 1"),
    "e3": NOTES("p. 17 &middot; worksheet task 1"),
    "e4": NOTES("p. 17 &middot; worksheet task 1"),
    "e5": NOTES("p. 8 &middot; the demand curve"),
    "e6": NOTES("p. 5&ndash;6 &middot; Engel curves"),
    "e7": NOTES("p. 18 &middot; review question 3"),
    "e8": NOTES("p. 18 &middot; review question 3"),

    "f1": NOTES("p. 18 &middot; review question 4"),
    "f2": NOTES("p. 18 &middot; review question 4"),
    "f3": NOTES("p. 18 &middot; review question 4"),
    "f4": NOTES("p. 18 &middot; review question 4"),
    "f5": NOTES("p. 18 &middot; review question 4"),
    "f6": NOTES("p. 18 &middot; review question 4"),
    "f7": NOTES("p. 10&ndash;11 &middot; substitution effect"),
    "f8": NOTES("p. 10&ndash;11 &middot; income effect"),

    "g1": NOTES("p. 17 &middot; worksheet task 3"),
    "g2": NOTES("p. 17 &middot; worksheet task 3"),
    "g3": NOTES("p. 17 &middot; worksheet task 3"),
    "g4": NOTES("p. 17 &middot; worksheet task 3"),
    "g5": NOTES("p. 17 &middot; worksheet"),
    "g6": NOTES("p. 14 &middot; the income effect"),
    "g7": NOTES("p. 16 &middot; worked example"),
    "g8": NOTES("p. 12 and 16 &middot; the Norwegian puzzle"),

    "h1": PS("A3.1 (6)"),
    "h2": PS("A3.1 (5)"),
    "h3": PS("A3.1 (5)"),
    "h4": PS("A3.2 (2)"),
    "h5": PS("A3.2 (3)"),
    "h6": PS("A3.2 (4)"),
}

for _q in (TANGENCY_QUESTIONS + DEMAND_QUESTIONS + TARIFF_QUESTIONS
           + LABOUR_QUESTIONS + SPECIAL_QUESTIONS):
    _q.source = STEP_SOURCES[_q.qid]
